name: Doc

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docs:
    name: Doc
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      with:
        lfs: 'true'
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10.4'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
